### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by TStansel** [rohitmucherla/python-checkers-group1#2]
Moving Pieces
Crown and kings
Tracking Pieces
Scoring
Determining turns for players

**Comment by TStansel** [comment]
Moving Pieces

if king==false{
    if diagonal space in front of piece open
        able to move to that spot
    if player piece and the diagonal from that piece is open
        able to jump player piece
}
else{
    if diagonal piece in front of piece or behind piece open
        able to move to that spot
    if player piece is in the diagonal and the diagonal from the player piece is open
        able to jump player piece
}

Crown and kings

if piece is at other end of board 
    piece is crowned and becomes king

Tracking Pieces

8x8 2D string Array
player1="O"
player2="X"
load in the O and X in the appropiate position 
update 2d array after each player move

Scoring

check playerTurn
then add 1 to either player1Score or player2Score

Determining turns for players

playerTurn = 0
if playerTurn==0 
    player1 takes turn and playerTurn=1
else if playerTurn==1 
    player2 takes turn and playerTurn = 0

**Comment by TStansel** [comment]
Do you have any thoughts on these? @BenjaminL97

**Comment by smcfizz** [comment]
I like the thought process on these but I would suggest a few adjustments:

Scoring

I'm unsure of the best way to calculate score, but if it were me I would probably opt for total games won rather than turns taken because otherwise the winner of the game would only have one more point than the loser and the score would end up being a relatively large and somewhat arbitrary number.

I would suggest we hold the score outside of the current game being ran and add to each player's score after they win a game. The pseudocode would look something like this:

subroutine endGame{ 
input winner 
winner.increaseScore
}

This subroutine would be called when the number of pieces a player has reaches 0 and would take the player who still has pieces as the winner. Because of the way this method works, we also need to adjust the algorithm for tracking pieces:

Tracking Pieces

8x8 2D char Array 
#seems like using String is unnecessary and would use more memory than necessary
#(Not like that matters much here, but still good practice)
player1="O"
player2="X"
load in the O and X in the appropiate position 
update 2d array after each player move

if piece is jumped{
jumped player piece count -= 1
if jumped player piece count == 0 {
endGame(pass player who jumped as input)
}
}

Sorry if my pseudocode isn't very good. I still think in Java so that probably shows. I hope these adjustments make sense! Let me know if you have any problem with them @ThomasStansel

**Comment by TStansel** [comment]
Scoring

I agree we should keep the score for games won rather than turns taken. Then to determine the winner we just check the player piece count at the end of each turn to make sure it above 0.

Tracking Pieces 

I like the "if piece is jumped" condition you added. Will make tracking and determining if the game has been won or not much easier. 

As well as adjusting the player piece count we should remove the related "O" or "X" from the 2d array.

If we wanted we could display the score as pieces are jumped. I am not sure if we are looking to do that or not but we just have to increment the respective players score after checking if a piece was jumped

If you see something I am over looking or any additions we could add lemme know.
@BenjaminL97

**Comment by smcfizz** [comment]
I think you nailed it! What we could do in terms of scoring is have a running score of how many pieces each player has jumped so far, so the players easily know who is winning, and then at the end of the game we could have a separate score that is based off of the total amount of games a player has won. What do you think? @ThomasStansel

**Comment by TStansel** [comment]
Sounds perfect! I'll update the text file so we can have all ideas in one place.
@BenjaminL97

**Comment by TStansel** [comment]
Moving Pieces

if king==false{
    if diagonal space in front of piece open
        able to move to that spot
    if player piece and the diagonal from that piece is open
        able to jump player piece
}
else{
    if diagonal piece in front of piece or behind piece open
        able to move to that spot
    if player piece is in the diagonal and the diagonal from the player piece is open
        able to jump player piece
}

Crown and kings

if piece is at other end of board 
    piece is crowned and becomes king

Tracking Pieces

8x8 2d char array
player1="O"
player2="X"
load in the O and X in the appropiate position 
update 2d array after each player move

if piece is jumped
    jumped player piece count -= 1
    remove piece jumped from 2d array
    localPlayerScore += 1
    if jumped player piece count == 0 
        endGame(pass player who jumped as input)

Scoring

if player1 == winner
    player1Wins += 1
else
    player2Wins += 1

Determining turns for players

playerTurn = 0
if playerTurn==0 
    player1 takes turn and playerTurn=1
else if playerTurn==1 
    player2 takes turn and playerTurn = 0

**Comment by TStansel** [comment]
Piece identification number
0=null
1=player 1  reg
2=player 2 reg
3 = player 1 king
4 = player 2 king
